### ISSUE TITLE
Can't find GT_splits

### ISSUE THREAD

**Issue by TGyAlDeen** [fandulu/DD-Net#1]
Dear, thanks for making this code available.
i couldn't access those files, it seem the website changed the structure of the files.
could you please help with it.
> GT_split_lists = glob.glob(C.data_dir + 'GT_splits/*.txt')
> GT_pose_list = glob.glob(C.data_dir + 'GT_joint_positions/*/*')

**Comment by fandulu** [comment]
Hi, try https://github.com/fandulu/DD-Net/blob/master/data/JHMDB/joint_positions.zip and https://github.com/fandulu/DD-Net/blob/master/data/JHMDB/splits.zip
