### ISSUE TITLE
Apply model to static gesture

### ISSUE THREAD

**Issue by DanielMao2015** [fandulu/DD-Net#12]
Hi, thank you for your nice work. And I am working about hand gesture recognition, concretely the static gesture.However, the DD-Net only accepts multiple frames as input. So in order to static hand gesture recognition, how should I modify the model? As I know, may I can capture mutiple frames of same hand gesture for training. And when applying, I just capture a series of video which corresponding to the num of frame of DD-Net and then get the final result as my label of static hand gesture.

**Comment by fandulu** [comment]
If I understand your question correctly, I suggest you to directly use something like https://www.pyimagesearch.com/2019/07/15/video-classification-with-keras-and-deep-learning/
