### ISSUE TITLE
accuracy changed in paper?

### ISSUE THREAD

**Issue by is-cs** [fandulu/DD-Net#14]
Hi

I saw that previously the best accuracy reported in your paper was 78% on J-HMDB. But now it is 77.2%. Can you explain why was this changed?

Thank you

**Comment by fandulu** [comment]
Sorry for this issue, I made a mistake in the previous version and obtained 78% on J-HMDB, after I corrected it, my model can only reach 77.2%, so I modified it in my new Arxiv version and github. If you want to compare with my work, plz regard my work as 77.2% on J-HMDB.

**Comment by is-cs** [comment]
Thank you for your clarification. Can you please also clarify if this 77.2% is the :
1. average of - best accuracies achieved on split1, 2 and 3. Or,
2. average of - averaged accuracies over multiple runs of split 1, 2 and 3.

Thank you

**Comment by fandulu** [comment]
average of - averaged accuracies over multiple runs of split 1, 2 and 3. The running records are still in the notebook file.

**Comment by is-cs** [comment]
Hi

Apologies for seeking clarification again. I see in the JHMDB Notebooks that you have run the model once per split, and averaged the best accuracy achieved in each split to reach 77.2%, so how is it average of - averaged accuracies over multiple runs of split1,2, and 3?

shouldn't "average of averaged accuracies" mean to run the model multiple times for each split, average multiple runs of each split, and then average these averaged results across splits?

Thank you
