### ISSUE TITLE
Unable to create conda env

### ISSUE THREAD

**Issue by fzqneo** [fandulu/DD-Net#16]
Nice work, authors. But I'm not able to create the env following the instruction.

```
$ conda env create -n ddnet -f DD-Net_env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:                                                       
  - libuuid==1.0.3=1                                                        
  - jpeg==9c=h470a237_0                                                     
  - nbconvert==5.3.1=py_1                                                   
  - qt==5.6.2=h50c60fd_8  
```
I'm running on Ubuntu 18.04 with conda 4.7.12. Any chance you ran on a different platform?

**Comment by fandulu** [comment]
It seems okay on my machine and I am sorry I also not sure how to fix it on your side. For this issue, I suggest just install TensorFlow backend Keras, most of the other dependencies may not be unnecessary and you can just delete them and run the code.
