### ISSUE TITLE
Is this extensible to other 2D/3D skeleton annotations?

### ISSUE THREAD

**Issue by giuseppepastore10** [fandulu/DD-Net#20]

**Comment by giuseppepastore10** [comment]
Hi, I'm interesting to know if you have evaluated the flexibility of this approach to other kind of body joints annotations, such as the common 21-joints.
Thank you in advance.

**Comment by fandulu** [comment]
Yes, just change the parameter to joints_num=21 and joints_dim=2/3  in every file.
