### ISSUE TITLE
method to average results across J-HMDB splits

### ISSUE THREAD

**Issue by is-cs** [fandulu/DD-Net#21]
Hi
I wish to understand your method to average the results obtained from 3 J-HMDB splits in detail. 
One way that i think this average could be taken is:
1. run the model for 600 epochs(say),  independently 10 times(say) on each split and get the best accuracy achieved in any epoch for every run. This gives us 10 best accuracies, one for each run.
2. average the 10 best test accuracies recorded from step 1 for each split.
3. Now, we have the 3 values, each value is the average of 10 runs on split 1,2, and 3, respectively.
4. average these 3 values to get the final average across 3 splits.

Is this method correct? If not, could you please elaborate your method?

Thank you

**Comment by fandulu** [comment]
Yes.
