### ISSUE TITLE
88% accuracy on JHMDB

### ISSUE THREAD

**Issue by YLTsai0609** [fandulu/DD-Net#23]
Hi, as you mentioned in README.md
We got an improvement from 77% to 88% by some bug fixing.
But I saw `JHMDB/jhmdb_1D_heavy.ipynb`, it was still 77%.
Do I miss anything?

**Comment by fandulu** [comment]
Hi, I did not update the running records on the ipynb. The record of split 1 can be found on the colab demo.
By the way, I think I put an incorrect number, it should be 83%, I corrected it now.
What I obtained is split 1: 85%, split 2: 81%, split 3: 82%, so the average should be 83%.
