### ISSUE TITLE
custom skeleton dataset and puppet scale

### ISSUE THREAD

**Issue by YLTsai0609** [fandulu/DD-Net#24]
Hi, thanks for your nice work!
Currently, I'm working on skeleton-based action recognition from the video clip.
The dataset in your paper, JHMDB is a well-annotated dataset with a puppet scaling factor for all skeleton.
the explanation on the JHMDB website is

```
1. See a sample annotation of the 15 positions at http://jhmdb.is.tue.mpg.de/puppet_tool
2. Due to the nature of the puppet annotation tool, all 15 joint positions are available even if they are not annotated when they are occluded or outiside the frame.
In this case, the joints are in the neutral puppet positions.
3. The right and left correspond to the right and left side of the annotated person. For example, a person facing the camera has his right side on the left side of the image, and a person back-facing the camera has his right side on the right side of the image.

(4) pos_world is the normalization of pos_img with respect to the frame size and puppet scale,Â
the formula is as below

pos_world(1,:,:) = (pos_img(1,:,:)/W-0.5)*W/H./scale;
pos_world(2,:,:) = (pos_img(2,:,:)/H-0.5)./scale;

W and H are the width and height of the frame, respectively.
```

But in a custom dataset extracting from a video clip. there is no puppet scaling factor.
In my experiments, accuracy on JHMDB without puppet scaling dropped the accuracy from 77% to 62%, which is huge.

So, is there any suggestion for tuning/keyword/formula/idea to simulate the puppet scaling factor?

Thanks!

**Comment by fandulu** [comment]
Hi, how do you think of normalizing the skeleton scale by using the spine length, e.g., ||p1-p2|| in puppet dataset.

**Comment by YLTsai0609** [comment]
@fandulu , thanks for your reply. I actually get 62% from ||p1-p2||. If I get anything. I'll update this!

**Comment by fandulu** [comment]
@YLTsai0609 ,  thanks for your comments. The JHMDB generated by a pose estimator contains more noise than the hand-annotated ones (used in this paper), I cannot improve the performance than you by DD-Net. 

Although 3D SHREC data is also very noisy, DD-Net works fine on it. I suppose that 2D noisy skeleton is more challenging than 3D noisy skeleton for DD-Net. It is a limitation of DD-Net.
