### ISSUE TITLE
Apply this model?

### ISSUE THREAD

**Issue by Kyle0936** [fandulu/DD-Net#7]
Thanks for sharing this nice model.

I'm pretty new to Machine Learning and I'm trying to classify several desired hand gestures in real-time. I'm wondering how to implement this model to do that.

**Comment by fandulu** [comment]
Hi, just use this code is only for off-line hand gesture recognition. To make it on-line, you can make a temporal window (e.g., window_size = 3s, steps = 0.5s) to convert the on-line stream to off-line clips. The prediction results of several clips could be averaged together to obtain a reasonable accuracy.
