### ISSUE TITLE
Maybe an error for GT_split_lists

### ISSUE THREAD

**Issue by anhminh3105** [fandulu/DD-Net#9]
I noticed in jhmdb_data_preprocessing.ipynb this snippet
```
GT_lists_1 = []
GT_lists_2 = []
GT_lists_3 = []
for file in GT_split_lists:
    if file.split('/')[-1].split('.')[0].split('_')[2] == 'split1':
        GT_lists_1.append(file) 
    elif file.split('/')[-1].split('.')[0].split('_')[2] == 'split2':
        GT_lists_2.append(file)
    elif file.split('/')[-1].split('.')[0].split('_')[2] == 'split3':
        GT_lists_3.append(file)
```
fetches just 1 word labels (e.g. catch, stand, push, etc.) and skipped 2 word labels (e.g. climb_stairs, kick_ball, shoot_gun, etc.). Therefore, the pickled dataset contains just 14 actions out of 21 actions of the JHMDB dataset. If this is intentional then you can close this issue but otherwise I made changes as follow to preprocess data of all 21 actions.
```
GT_lists_1 = []
GT_lists_2 = []
GT_lists_3 = []
for file in GT_split_lists:
    if file.split('/')[-1].split('.')[0].split('_')[-1] == 'split1':
        GT_lists_1.append(file) 
    elif file.split('/')[-1].split('.')[0].split('_')[-1] == 'split2':
        GT_lists_2.append(file)
    elif file.split('/')[-1].split('.')[0].split('_')[-1] == 'split3':
        GT_lists_3.append(file)
```

**Comment by fandulu** [comment]
Thanks very much for pointing out this error, you are correct and I had a bug there. I rerun the experiments and report the new performance. The best performance is achieved by 1.82 M parameters other than 0.5M parameters, and the best accuracy is 77.2 other than 78.0. Besides, the performance of 0.15M model drops significantly. I will also correct my paper based on the new results.
